feat: Blessings
opentibiabr/otclient pull request #825
Opened 2024-07-21 22:49 UTC by kokekanon

# Description
![bless](https://github.com/user-attachments/assets/55f7b2d5-32dc-4d51-924c-f04ef4c84ccf)
I know there are some visual errors, like

-  the close and history buttons are on the left. 
- the title of the mini windows is not visible
-  the history part.
- the images are probably out of order

I don't use css/html

 im 8.6 player. I don't know how it works.

## Behavior

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2024-07-21 23:11 UTC, luanluciano93 requested changes

2024-07-21 23:11 UTC, luanluciano93 commented on modules/game_blessing/style.otui
> +
remove 2 spaces

2024-07-21 23:11 UTC, luanluciano93 commented on modules/game_blessing/blessing.lua
> +end
space

2024-07-21 23:11 UTC, luanluciano93 commented on modules/game_blessing/blessing.html
> +  }
space

2024-07-21 23:11 UTC, luanluciano93 commented on modules/game_blessing/blessing.lua
> +        local date = os.date("%Y-%m-%d, %H:%M:%S", entry.timestam)
timestamp

2024-07-21 23:11 UTC, luanluciano93 commented on src/client/game.h
> +    void requestBless();
space

2024-07-21 23:11 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    for (uint8_t i = 0; i < data.totalBless; ++i) {
I don't think it's necessary to store totalBless in data

2024-08-08 10:49 UTC, luanluciano93 requested changes

2024-08-08 10:49 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    for (uint8_t i = 0; i < logCount; ++i) {
```suggestion
    const uint8_t logCount = msg->getU8();
    for (auto i = 0; i < logCount; ++i) {
```

2024-08-08 10:49 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    for (uint8_t i = 0; i < data.totalBless; ++i) {
```suggestion
    for (auto i = 0; i < data.totalBless; ++i) {
```

2024-08-08 10:49 UTC, luanluciano93 commented on modules/game_blessing/blessing.lua
> +
remove space

2024-08-08 10:49 UTC, luanluciano93 commented on modules/game_blessing/blessing.lua
> +
remove space

2024-08-12 18:35 UTC, closed without merging

2024-08-13 00:07 UTC, kokekanon commented
need to make a `git reset --hard hash` sorry open other pr