feat: item duration display UI (GameThingClock)
opentibiabr/otclient pull request #834
Opened 2024-07-28 18:07 UTC by kokekanon

# Description

I don't know if it's the best code, but it works xd

## Behavior

### **Actual**

Do this and that doesn't happens

### **Expected**
OTC  ------------------------------- Clipsoft
![otcs](https://github.com/user-attachments/assets/96328017-9f10-4b42-963d-4ea606e4a799) ![clipsoftdf](https://github.com/user-attachments/assets/aefed860-e2d3-47b9-b127-5ba94f860396)

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2024-07-29 09:43 UTC, luanluciano93 commented
very good

2024-08-08 10:45 UTC, luanluciano93 requested changes

2024-08-08 10:45 UTC, luanluciano93 commented on src/client/item.h
> +    void setDurationTime(uint32_t durationTime) { m_durationTime = durationTime; }
```suggestion
    void setDurationTime(const uint32_t durationTime) { m_durationTime = durationTime; }
```

2024-08-12 17:52 UTC, Nottinghster approved these changes

2024-08-12 23:28 UTC, luanluciano93 approved these changes

2024-08-12 23:28 UTC, merged