feat: compatibility with 13.40
opentibiabr/otclient pull request #840
Opened 2024-08-09 04:48 UTC by kokekanon

# Description

https://github.com/opentibiabr/canary/pull/2802/files

| Changes pr canary  	| Send/get 	| Done 	|
|--------------------	|----------	|------	|
| Cyclopedia         	| get      	|    ✅ in future pr  	|
| Wheel              	| get      	|      	|
| Quick Loot         	| get      	|      	|
| onRecvFirstMessage 	| send     	|      	|
| parseSetOutfit     	| send     	|      	|
| sendContainer      	| get      	|  ✅* WÏP|
| trade npc          	| get      	|   ✅   	|

can Login 
can Trade Npc

test in 8.6 ,13,32,13.40
in 1100 I think there is a bug but it is from canary

## Behavior

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2024-08-09 05:28 UTC, luanluciano93 requested changes

2024-08-09 05:28 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    }
```suggestion
    if (g_game.getClientVersion() >= 1340) {
        msg->getU8();
        msg->getU8();
    }
```

2024-08-09 05:28 UTC, luanluciano93 commented on modules/gamelib/game.lua
> +        1286, 1287, 1291, 1300, 1310, 1311, 1314, 1316, 1320, 1321, 1322, 1332 , 1340}
```suggestion
        1286, 1287, 1291, 1300, 1310, 1311, 1314, 1316, 1320, 1321, 1322, 1332, 1334, 1336, 1337, 1340}
```

2024-08-09 05:28 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    if (g_game.getClientVersion() >= 1340) {
```suggestion
    if (g_game.getClientVersion() >= 1334) {
```

2024-08-12 17:53 UTC, Nottinghster approved these changes

2024-08-12 23:29 UTC, luanluciano93 approved these changes

2024-08-13 00:57 UTC, luanluciano93 approved these changes

2024-08-13 00:57 UTC, merged