fix getItems
opentibiabr/otclient pull request #892
Opened 2024-09-28 01:32 UTC by luanluciano93

![image](https://github.com/user-attachments/assets/d54946f8-e3a9-45af-b20c-d47a49211c3d)

2024-09-29 11:56 UTC, bateunatrave commented
Now the trade window is appearing, but when the other player's item appears, the crash occurs.

2024-10-01 16:42 UTC, luanluciano93 commented
> Now the trade window is appearing, but when the other player's item appears, the crash occurs.


Can you use the deputy to see where the crash is occurring, like the PR image?

2024-10-02 16:35 UTC, kokekanon commented
test in 13.40

in my test there is no crash, but when I accept the trade

```lua
ERROR: ProtocolGame parse message exception (357 bytes, 348 unread, last opcode is 0x89 (137), prev opcode is 0xffffffff (-1)): unhandled opcode 137
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1340)
```

in 8.6 this error does not occur

2024-10-04 10:16 UTC, nekiro requested changes

2024-10-04 10:16 UTC, nekiro commented on src/client/protocolgameparse.cpp
> +    std::vector<ItemPtr> items(count);
`items.reserve(count)`

2024-10-04 10:16 UTC, nekiro commented on src/client/protocolgameparse.cpp
>          items[i] = getItem(msg);
`items.push_back(getItem(msg)`

2024-10-04 16:20 UTC, nekiro approved these changes

2024-10-05 12:26 UTC, merged