fix: game_outfit custom compatible with canary
opentibiabr/otclient pull request #962
Opened 2024-11-07 19:22 UTC by kokekanon

# Description

# feat:  server send feature to enable / disable
server:
![image](https://github.com/user-attachments/assets/a52158ec-fb1f-490f-823c-81bc54c1dc54)
https://github.com/opentibiabr/canary/pull/3061

commits server : 
https://github.com/opentibiabr/canary/pull/3061/commits/74ea55f7d1cd035b57d1ca97f330fbb158f1837a

# fix game_outfit : outfit/mount in store

![image](https://github.com/user-attachments/assets/03b78ba0-e75b-4db9-bbd6-74962e4bad94)
![image](https://github.com/user-attachments/assets/1d0af29b-4ac7-4b64-9f10-6528ec11c029)

# fix: minor error cyclopedia  13.40

## Behavior

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2024-11-08 00:43 UTC, luanluciano93 requested changes

2024-11-08 00:43 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +        bool enabled = msg->getU8() > 0;
```suggestion
        const auto feature = static_cast<Otc::GameFeature>(msg->getU8());
        const bool enabled = static_cast<bool>(getU8());
```

2024-11-08 00:43 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +            outfitList.emplace_back(outfitId, outfitName, outfitAddons,outfitMode);
```suggestion
            outfitList.emplace_back(outfitId, outfitName, outfitAddons, outfitMode);
```

2025-01-05 19:18 UTC, luanluciano93 commented on src/client/luavaluecasts_client.cpp
> +        g_lua.setField("shaders");
familiar?

2025-01-22 12:21 UTC, luanluciano93 requested changes

2025-01-22 12:21 UTC, luanluciano93 commented on modules/game_outfit/outfit.lua
> +                    {window.appearance.settings.title, ServerData.title}}
```suggestion
    local checks = {
        {window.preview.options.showWings, ServerData.wings},
        {window.preview.options.showAura, ServerData.auras},
        {window.preview.options.showShader, ServerData.shaders},
        {window.preview.options.showBars, ServerData.healthBars},
        {window.preview.options.showEffects, ServerData.effects},
        {window.preview.options.showTitle, ServerData.title},
        {window.preview.options.showFamiliar, ServerData.familiars},
        {window.appearance.settings.familiar, ServerData.familiars},
        {window.appearance.settings.wings, ServerData.wings},
        {window.appearance.settings.aura, ServerData.auras},
        {window.appearance.settings.shader, ServerData.shaders},
        {window.appearance.settings.healthBar, ServerData.healthBars},
        {window.appearance.settings.effects, ServerData.effects},
        {window.appearance.settings.title, ServerData.title},
    }
```

2025-01-22 12:21 UTC, luanluciano93 commented on modules/game_outfit/outfit.lua
> +
```suggestion
```

2025-01-22 12:21 UTC, luanluciano93 commented on modules/game_outfit/outfit.lua
> +        local player = g_game.getLocalPlayer()
?

2025-01-22 12:21 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    std::vector<std::tuple<uint16_t, std::string> > familiarList;
familiarMode?

2025-01-22 15:25 UTC, kokekanon commented on src/client/protocolgameparse.cpp
> +    std::vector<std::tuple<uint16_t, std::string> > familiarList;
that is used here
    
    g_game.processOpenOutfitWindow(currentOutfit, outfitList, mountList, **familiarList**, wingList, auraList, effectList, shaderList);

2025-01-22 16:45 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    std::vector<std::tuple<uint16_t, std::string> > familiarList;
I wanted to ask why you added the mode to outfits and mounts, and not to family members

2025-01-22 16:46 UTC, luanluciano93 commented on modules/game_outfit/outfit.lua
> +        local player = g_game.getLocalPlayer()
Is "player" used here?

2025-01-22 17:23 UTC, kokekanon commented on src/client/protocolgameparse.cpp
> +    std::vector<std::tuple<uint16_t, std::string> > familiarList;
I don't use canary, I don't know many things about familiar, but at the time I test, I didn't see in cipsof that it was used(ui/ux).

![image](https://github.com/user-attachments/assets/894fc252-3d43-4267-bf64-5f6a05f0b808)

could you share a picture of a familiar in  cipsoft (outfit) ?

2025-01-22 17:40 UTC, kokekanon commented on modules/game_outfit/outfit.lua
> +        local player = g_game.getLocalPlayer()
no, I deleted it

2025-01-23 21:44 UTC, merged