fix: packet Canary PR : "cyclopedia house auction"  # 3022
opentibiabr/otclient pull request #970
Opened 2024-11-18 22:30 UTC by kokekanon

| SEND                                    	| Packet 	| test 	| lua - otui 	|
|-----------------------------------------	|--------	|------	|------------	|
| sendCyclopediaHouseAuction              	|        0xAD (173)	|      	|            	|

| GET                                    	| Packet 	| test 	| lua - otui 	|
|-----------------------------------------	|--------	|------	|------------	|
| GameServerCyclopediaHouseAuctionMessage 	| 0xC3 (195)  	|      	|            	|
| GameServerCyclopediaHousesInfo          	| 0xC6  (198) 	| ✅    	|            	|
| GameServerCyclopediaHouseList           	| 0xC7   (199)	|      	|            	|

# Description

I was test. this pr https://github.com/opentibiabr/canary/pull/3022

PR sent packets when logging in
```lua
ERROR: ProtocolGame parse message exception (12336 bytes, 5967 unread, last opcode is 0xc6 (198), prev opcode is 0x9f (159)): unhandled opcode 198
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1340)
```

I solved that problem, the rest is theoretical, I don't know how to test that.

last commits  

> `26a2d60 `
> "Merge branch 'main' into test-house"
>  on Nov 12, 2024, 02:28 PM

 

## Behavior

### **Actual**

Packet error

### **Expected**

Do this and that happens

## Fixes

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested

untest ,  until the end of the pr

**Test Configuration**:

  - Server Version: 13.40 `26a2d60`
  - Client: this PR
  - Operating System: 11
 
## Checklist

  - [x] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

# ONLY APPROVE IF PR CANARY #  3022 IS APPROVED. if not close xd

2024-11-25 16:09 UTC, luanluciano93 requested changes, later dismissed

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/game.cpp
> +void Game::requestSendCyclopediaHouseAuction(const Otc::CyclopediaHouseAuctionType_t type, const uint32_t houseId, const uint32_t timestamp, const uint64_t bidValue, const std::string_view& name)
```suggestion
void Game::requestSendCyclopediaHouseAuction(const Otc::CyclopediaHouseAuctionType_t type, const uint32_t houseId, const uint32_t timestamp, const uint64_t bidValue, const std::string_view name)
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/game.h
> +    void requestSendCyclopediaHouseAuction(const Otc::CyclopediaHouseAuctionType_t type, const uint32_t houseId, const uint32_t timestamp = 0, const uint64_t bidValue = 0, const std::string_view& nam
```suggestion
    void requestSendCyclopediaHouseAuction(const Otc::CyclopediaHouseAuctionType_t type, const uint32_t houseId, const uint32_t timestamp = 0, const uint64_t bidValue = 0, const std::string_view name = "");
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/protocolgame.h
> +    void sendCyclopediaHouseAuction(const Otc::CyclopediaHouseAuctionType_t type, const uint32_t houseId, const uint32_t timestamp, const  uint64_t bidValue, const std::string_view& name);
```suggestion
    void sendCyclopediaHouseAuction(const Otc::CyclopediaHouseAuctionType_t type, const uint32_t houseId, const uint32_t timestamp, const  uint64_t bidValue, const std::string_view name);
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    if (const uint8_t typeValue = msg->getU8(); typeValue == 1) {
```suggestion
    const uint8_t typeValue = msg->getU8();
    if (typeValue == 1) {
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    for (auto i = 0; i < size; ++i) {
```suggestion
    const uint16_t housesList = msg->getU16(); // g_game().map.houses.getHouses()
    for (auto i = 0; i < housesList; ++i) {
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/protocolgameparse.cpp
> +    }
```suggestion
    const uint16_t housesCount = msg->getU16(); // housesCount
    for (auto i = 0; i < housesCount; ++i) {
        msg->getU32(); // clientId
        msg->getU8(); // 0x00 = Renovation, 0x01 = Available
        
        const auto type = static_cast<Otc::CyclopediaHouseState_t>(msg->getU8());
        switch (type) {
            case Otc::CYCLOPEDIA_HOUSE_STATE_AVAILABLE: {
                std::string bidderName = msg->getString(); 
                const auto isBidder = static_cast<bool>(msg->getU8());
                msg->getU8(); // disableIndex

                if (!bidderName.empty()) {
                    msg->getU32(); // bidEndDate
                    msg->getU64(); // highestBid
                    if (isBidder) {
                        msg->getU64(); // bidHolderLimit
                    }
                }
                break;
            }
            case Otc::CYCLOPEDIA_HOUSE_STATE_RENTED: {
                msg->getString(); // ownerName
                msg->getU32(); // paidUntil
                
                const auto isRented = static_cast<bool>(msg->getU8());
                if (isRented) {
                    msg->getU8(); // unknown
                    msg->getU8(); // unknown
                }
                break;
            }
            case Otc::CYCLOPEDIA_HOUSE_STATE_TRANSFER: {
                msg->getString(); // ownerName
                msg->getU32(); // paidUntil
                const auto isOwner = static_cast<bool>(msg->getU8());
                if (isOwner) {
                    msg->getU8(); // unknown
                    msg->getU8(); // unknown
                }
                msg->getU32(); // bidEndDate
                msg->getString(); // bidderName
                msg->getU8(); // unknown
                msg->getU64(); // internalBid
                
                const auto isNewOwner = static_cast<bool>(msg->getU8());
                if (isNewOwner) {
                    msg->getU8(); // acceptTransferError
                    msg->getU8(); // rejectTransferError
                }

                if (isOwner) {
                    msg->getU8(); // cancelTransferError
                }
                break;
            }
            case Otc::CYCLOPEDIA_HOUSE_STATE_MOVEOUT: {
                msg->getString(); // ownerName
                msg->getU32(); // paidUntil

                const auto isOwner = static_cast<bool>(msg->getU8());
                if (isOwner) {
                    msg->getU8(); // unknown
                    msg->getU8(); // unknown
                    msg->getU32(); // bidEndDate
                    msg->getU8(); // unknown
                } else {
                    msg->getU32(); // bidEndDate
                }

                break;
            }
        }
    }
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/protocolgamesend.cpp
> +void ProtocolGame::sendCyclopediaHouseAuction(const Otc::CyclopediaHouseAuctionType_t type, const uint32_t houseId, const uint32_t timestamp, const uint64_t bidValue, const std::string_view& name)
```suggestion
void ProtocolGame::sendCyclopediaHouseAuction(const Otc::CyclopediaHouseAuctionType_t type, const uint32_t houseId, const uint32_t timestamp, const uint64_t bidValue, const std::string_view name)
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/protocolgamesend.cpp
> +
```suggestion
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/protocolgamesend.cpp
> +
```suggestion
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/protocolgamesend.cpp
> +
```suggestion
```

2024-11-25 16:09 UTC, luanluciano93 commented on src/client/protocolgamesend.cpp
> +
```suggestion
```

2024-11-25 16:12 UTC, kokekanon commented on src/client/protocolgameparse.cpp
> +    if (const uint8_t typeValue = msg->getU8(); typeValue == 1) {
I did that before, but sonarbot sends that recommendation. 

"-Use the init-statement to declare "typeValue" inside the if statement."

2024-12-31 18:50 UTC, kokekanon commented
canary's pr # 3022  was approved today.


 this pr can now be merged.

2025-01-03 19:42 UTC, majestyotbr approved these changes

2025-01-03 19:45 UTC, merged